name:                integration-patterns
version:             0.1.0.0
github:              "EmilijusS/integration-patterns"
license:             BSD3
author:              "Emilijus Stankus"
maintainer:          "emilijus@gmail.com"
copyright:           "2019 Emilijus Stankus"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Enterprise Integration Patterns implemented using Pipes library

dependencies:
- base >= 4.7 && < 5
- stm
- async
- containers
- pipes
- pipes-concurrency
- extra
- random

library:
  source-dirs: src

executables:
  integration-patterns-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - integration-patterns

tests:
  integration-patterns-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - integration-patterns
